###
# Copyright (2016-2019) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
---
# This resource is only available on HPE Synergy
- hosts: all
  vars:
    - config: "{{ playbook_dir }}/oneview_config.json"
  tasks:
    - name: Gather facts about all SAS Interconnects
      oneview_sas_interconnect_facts:
        config: "{{ config }}"
      delegate_to: localhost

    - debug: var=sas_interconnects

    - name: Gather paginated, filtered and sorted facts about SAS Interconnects
      oneview_sas_interconnect_facts:
        config: "{{ config }}"
        params:
          start: 0
          count: 3
          sort: 'name:descending'
          filter: "softResetState='Normal'"

    - debug: var=sas_interconnects

    - name: Gather facts about a SAS Interconnect by name
      oneview_sas_interconnect_facts:
        config: "{{ config }}"
        name: "0000A66103, interconnect 1"
      delegate_to: localhost

    - debug: var=sas_interconnects
