###
# Copyright (2016-2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
---
###
# This playbook is only compatible with HPE Synergy Enclosures
###
- hosts: all
  vars:
    - config: "{{ playbook_dir }}/oneview_config.json"
    # Set the existent Deployment Plan name
    - deployment_plan_name: "Deployment Plan"
    # Set the URI of an existent Enclosure Group (OS Deployment enabled)
    - enclosure_group_uri: '/rest/enclosure-groups/184736fb-c64b-420f-b73f-ed62a9d9ea43'
    # Set the URI of an existent Server Hardware type
    - server_hardware_type_uri: '/rest/server-hardware-types/09A00DB8-B47A-4EC1-89BF-7962E0CE0B80'
    # Set the Network URI enabled for OS Deployment
    - network_uri : '/rest/ethernet-networks/062ff757-6ddd-47b4-b5c9-634498b85823'
    # OS Custom Attributes file name (for example only), comment this line to skip file creation/reading
    - os_custom_attributes_file_name: '{{ playbook_dir }}/vars/os_attributes.yaml'
    # Enable/Disable the delete of the Server Profile at the end (demonstration only)
    - automatically_delete_created_profile: False
  tasks:
    - name: 1. Gather OS Custom Attributes from OS Deployment Plan
      oneview_os_deployment_plan_facts:
        config: "{{ config }}"
        name: "{{ deployment_plan_name }}"
        options:
          # This option will generate an os_deployment_plan_custom_attributes facts in a Server Profile format
          - osCustomAttributesForServerProfile
      delegate_to: localhost

    # Copy contents of the fact to a local file, allowing the user to edit it
    - name: "2. [Optional] Exporting OS Custom Attributes to the file: {{ os_custom_attributes_file_name }}"
      copy: content="{{ os_deployment_plan_custom_attributes | to_nice_yaml }}" dest="{{ os_custom_attributes_file_name }}"
      when: os_custom_attributes_file_name is defined
      delegate_to: localhost

    # Load variables from the file (this play register os_custom_attributes_for_server_profile variable)
    - name: "3. [Optional] Reading OS Custom Attributes from the file: {{ os_custom_attributes_file_name }}"
      include_vars: "{{ playbook_dir }}/vars/os_attributes.yaml"
      when: os_custom_attributes_file_name is defined
      delegate_to: localhost

    - name: 4. Select the variable (from file or from oneview_os_deployment_plan_facts output)
      set_fact: os_custom_attributes_for_server_profile="{{ os_deployment_plan_custom_attributes.os_custom_attributes_for_server_profile }}"
      when: not os_custom_attributes_file_name is defined
    - debug: var=os_custom_attributes_for_server_profile

    - name: 5. Create the Server Profile
      oneview_server_profile:
         config: "{{ config }}"
         data:
           name: "{{ inventory_hostname }}"
           serverHardwareTypeUri: "{{ server_hardware_type_uri }}"
           enclosureGroupUri: "{{ enclosure_group_uri }}"
           boot:
              manageBoot: true
              order:
              - HardDisk
           bootMode:
              manageMode: true
              mode: UEFIOptimized
              pxeBootPolicy: Auto
           connections:
            - id: 1
              portId: "Mezz 3:1-a"
              name: 'connection1'
              functionType: 'Ethernet'
              networkUri: '{{ network_uri }}'
              requestedMbps: 2500
              requestedVFs: "Auto"
              boot:
                priority: Primary
                initiatorNameSource: ProfileInitiatorName
            - id: 2
              portId: "Mezz 3:2-a"
              name: 'connection2'
              functionType: 'Ethernet'
              networkUri: '{{ network_uri }}'
              requestedMbps: 2500
              requestedVFs: "Auto"
              boot:
                priority: Secondary
                initiatorNameSource: ProfileInitiatorName

           # OS Deployment Settings
           osDeploymentSettings:
              # This came from the oneview_os_deployment_plan_facts module
              # If you prefer, you may provide an osDeploymentPlanName attribute instead.
              osDeploymentPlanUri: "{{ os_deployment_plans.0.uri }}"
              # os_custom_attributes_for_server_profile may have been loaded from the file or
              # from the oneview_os_deployment_plan_facts output variable
              osCustomAttributes: "{{ os_custom_attributes_for_server_profile }}"
      delegate_to: localhost
    - debug: var=server_profile

    - name: 6. Delete the Server Profile
      oneview_server_profile:
         config: "{{ config }}"
         state: "absent"
         data:
           name: "{{ inventory_hostname }}"
      when: automatically_delete_created_profile
      delegate_to: localhost
